version: '3.8'

services:
  web:
    build: .
    environment:
      - SECRET_KEY=vbexlzvrbvmzgmxh
    command: python /projects/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/projects
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    ports: 
      - 5432:5432
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: